server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd #如果使用字符串型表示，用此格式
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用数值表示timestamp日期
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
  thymeleaf:
    cache: false #关闭缓存
  resources:
    static-locations: classpath:/static/,classpath:/public/

logging:
  file: target/app.log
  level:
    ROOT: warn
    com.example: trace
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.springboot.dao